---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - env:
        - name: MONGO_DB_CONNECTION_STRING
          value: mongodb://mongo:27017/sample
        image: vinaykumar0524/persistence:1.0
        name: sample
        ports:
        - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: node
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31200
  selector:
    app: node

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo




  
